### ISSUE TITLE
VisibleForTesting should get a @Retention annotation

### ISSUE THREAD

**Issue by koppor** [nbbrd/java-design-util#174]
Most annotations do have a `@Retention` annotation. [Default is `CLASS`](https://docs.oracle.com/javase/8/docs/api/java/lang/annotation/RetentionPolicy.html). I think, `VisibleForTesting` should get a `SOURCE` annotation, but I might be wrong. Therefore, I ask to make the Retention explicit by making an annotation.

**Comment by koppor** [comment]
I think, I know the reason. This is a variant of Google's VisbileForTesting annotation, which enable class compilation, because of checking using ErrorProne: http://errorprone.info/bugpattern/RestrictedApi

---

```java
/**
 * Annotates a program element that exists, or is more widely visible than otherwise necessary, only
 * for use in test code.
 *
 * <p><b>Do not use this interface</b> for public or protected declarations: it is a fig leaf for
 * bad design, and it does not prevent anyone from using the declaration---and experience has shown
 * that they will. If the method breaks the encapsulation of its class, then its internal
 * representation will be hard to change. Instead, use <a
 * href="http://errorprone.info/bugpattern/RestrictedApi">RestrictedApiChecker</a>, which enforces
 * fine-grained visibility policies.
 *
 * @author Johannes Henkel
 */
@GwtCompatible
public @interface VisibleForTesting {
}
```

**Comment by charphi** [comment]
Well, my intention was for this annotation to be visible to source only.

**Comment by charphi** [comment]
I've just made the change in f12608ba19d61c7d4b6402dac7650cd8948638e8
